"""Set certain fields to Not Null

Revision ID: 905295df2f88
Revises: 224eee752625
Create Date: 2020-02-11 23:20:15.393681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '905295df2f88'
down_revision = '224eee752625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('artist', 'seeking_venue',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('venue', 'genres',
                    existing_type=postgresql.ARRAY(sa.VARCHAR()),
                    nullable=False)
    op.alter_column('venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('venue', 'seeking_talent',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('venue', 'seeking_talent',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('venue', 'genres',
                    existing_type=postgresql.ARRAY(sa.VARCHAR()),
                    nullable=True)
    op.alter_column('venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('artist', 'seeking_venue',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    # ### end Alembic commands ###
